apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-db
  labels:
    app: drupal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-db
  template:
    metadata:
      labels:
        app: drupal-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "drupal"
            - name: MYSQL_USER
              value: "drupal"
            - name: MYSQL_PASSWORD
              value: "drupalpassword"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: drupal-db-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: drupal-db-data
          persistentVolumeClaim:
            claimName: drupal-db-pvc