apiVersion: batch/v1
kind: Job
metadata:
  name: drupal-install
  labels:
    app: drupal-install
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: drupal-install
    spec:
      restartPolicy: OnFailure
      containers:
      - name: drupal-installer
        image: localhost:32000/custom-drupal:latest
        env:
        - name: DRUPAL_DATABASE_HOST
          value: "drupal-db"
        - name: DRUPAL_DATABASE_PORT
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "drupal"
        - name: DRUPAL_DATABASE_USERNAME
          value: "drupal"
        - name: DRUPAL_DATABASE_PASSWORD
          value: "drupalpassword"
        - name: DRUPAL_HASH_SALT
          value: "f9a8u7c0xzVCBVDNkLsKqUB02PU9EYhZxLd1jQUi"
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command: ["/usr/local/bin/drupal-install-job.sh"]
        volumeMounts:
        - name: drupal-files
          mountPath: /var/www/html/sites/default/files
      volumes:
      - name: drupal-files
        persistentVolumeClaim:
          claimName: drupal-files-pvc