apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wordpress resources
  - wordpress/wordpress-db-pvc.yaml
  - wordpress/wordpress-db-deployment.yaml
  - wordpress/wordpress-db-service.yaml
  - wordpress/wordpress-pvc.yaml
  - wordpress/wordpress-config.yaml
  - wordpress/wordpress-deployment.yaml
  - wordpress/wordpress-service.yaml

  # Chat resources
  - chat/db/chat-db-pvc.yaml
  - chat/db/chat-db-deployment.yaml
  - chat/db/chat-db-service.yaml
  - chat/backend/chat-backend-deployment.yaml
  - chat/backend/chat-backend-service.yaml
  - chat/frontend/chat-frontend-deployment.yaml
  - chat/frontend/chat-frontend-service.yaml
  - chat/redis/redis-deployment.yaml
  - chat/redis/redis-service.yaml
  
  # AI resources
  - ai/frontend/ai-frontend-deployment.yaml
  - ai/frontend/ai-frontend-service.yaml
  - ai/backend/ai-backend-deployment.yaml
  - ai/backend/ai-backend-service.yaml
  
  # Secrets
  - secrets/azure-secrets.yaml