apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  type: NodePort
  ports:
  - port: 88  # Conform cerințelor: expus pe portul 88
    targetPort: 80  # Nginx container port
    nodePort: 30088
    protocol: TCP
  selector:
    app: chat-backend