apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
  labels:
    app: ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
      - name: ai-backend
        image: localhost:32000/ai-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: storage-connection-string
        - name: AZURE_CONTAINER_NAME
          value: "images"
        - name: AZURE_OCR_ENDPOINT
          value: "https://temaocr.cognitiveservices.azure.com/"
        - name: AZURE_OCR_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: ocr-api-key
        - name: AZURE_SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: sql-connection-string