apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
spec:
  type: NodePort
  ports:
  - port: 90  # Conform cerințelor: expus pe portul 90
    targetPort: 80  # Nginx container port
    nodePort: 30090
    protocol: TCP
  selector:
    app: chat-frontend