apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: microk8s-hostpath