apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 4  # Required by tema: 4 replicas
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - wordpress
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: wordpress-init
        image: wordpress:6.6-apache
        command: ['/bin/bash', '/init-scripts/init-wordpress.sh']
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db:3306"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppassword123"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        - name: init-scripts
          mountPath: /init-scripts
      containers:
      - name: wordpress
        image: wordpress:6.6-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db:3306"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppassword123"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
            define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
            define('FS_METHOD', 'direct');
            define('WP_MEMORY_LIMIT', '256M');
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /wp-admin/admin-ajax.php
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /wp-admin/admin-ajax.php
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 10
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-files-pvc
      - name: init-scripts
        configMap:
          name: wordpress-config
          defaultMode: 0755