apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-shared-pvc
spec:
  accessModes:
    - ReadWriteMany  # Important: permite acces la multiple pod-uri
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      # Init container to ensure proper permissions
      - name: fix-permissions
        image: busybox:1.36
        command: ['sh', '-c']
        args:
          - |
            echo "Setting up WordPress directory permissions..."
            mkdir -p /var/www/html
            chmod -R 777 /var/www/html
            echo "Permissions fixed"
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      containers:
      - name: wordpress
        image: localhost:32000/custom-wordpress:latest
        imagePullPolicy: Always
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppassword"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_TABLE_PREFIX
          value: "wp_"
        - name: WORDPRESS_DEBUG
          value: "false"
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /wp-admin/install.php
            port: 80
            httpHeaders:
            - name: Host
              value: "localhost"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-shared-pvc