apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: wait-for-db
        image: wordpress:6.6-apache
        command: ['bash', '/scripts/wait.sh']
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db:3306"
        volumeMounts:
        - name: db-check-script
          mountPath: /scripts
      containers:
      - name: wordpress
        image: wordpress:6.6-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db:3306"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          value: "wppassword123"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
            define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
            define('FS_METHOD', 'direct');
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 40
          periodSeconds: 15
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-files-pvc
      - name: db-check-script
        configMap:
          name: wordpress-config