apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  storage-connection-string: your_storage_connection_string
  ocr-api-key: your_ocr_api_key
  sql-connection-string: your_sql_connection_string
